[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TkInforHard"
version = "1.1.0"
description = "Professional reusable UI component framework for tkinter and ttkbootstrap."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ttkbootstrap>=1.10.1",
    "Pillow>=10.0.0",
]
authors = [
    { name = "Inforhard" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: User Interfaces",
]

[tool.setuptools.packages.find]
include = ["TkInforHard*"]
