"""Typography tokens."""

FONT_FAMILY = "Segoe UI"
FONT_FAMILY_MONO = "Consolas"

FONT_SIZE_XS = 9
FONT_SIZE_SM = 10
FONT_SIZE_MD = 11
FONT_SIZE_LG = 14
FONT_SIZE_XL = 18
FONT_SIZE_2XL = 24

FONT_WEIGHT_REGULAR = "normal"
FONT_WEIGHT_MEDIUM = "normal"
FONT_WEIGHT_BOLD = "bold"

LINE_HEIGHT_TIGHT = 1.15
LINE_HEIGHT_NORMAL = 1.35
LINE_HEIGHT_RELAXED = 1.55

